// <auto-generated />
using System;
using Beeexy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beeexy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BeeexyDbContext))]
    [Migration("20260822035009_Phase42ClinicalDefinitionPackages")]
    partial class Phase42ClinicalDefinitionPackages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beeexy.Domain.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_normalized_email");

                    b.ToTable("accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_accounts_status", "\"status\" IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.EmailAuthenticationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("otp_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_email_authentication_challenges");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_email_authentication_challenges_pending_expiry")
                        .HasFilter("\"status\" = 'pending' AND \"consumed_at\" IS NULL");

                    b.ToTable("email_authentication_challenges", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_email_authentication_challenges_attempt_count", "\"attempt_count\" >= 0");

                            t.HasCheckConstraint("ck_email_authentication_challenges_consumed", "(\"status\" = 'consumed' AND \"consumed_at\" IS NOT NULL) OR (\"status\" <> 'consumed' AND \"consumed_at\" IS NULL)");

                            t.HasCheckConstraint("ck_email_authentication_challenges_expiration", "\"expires_at\" > \"created_at\"");

                            t.HasCheckConstraint("ck_email_authentication_challenges_status", "\"status\" IN ('pending', 'consumed', 'expired')");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_external_identities");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_external_identities_account_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_provider_subject");

                    b.ToTable("external_identities", "identity");
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ParentSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_session_id");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_refresh_sessions");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_sessions_family_id");

                    b.HasIndex("ParentSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_parent_session_id")
                        .HasFilter("\"parent_session_id\" IS NOT NULL");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_refresh_token_hash");

                    b.HasIndex("AccountId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_sessions_active_account_expiry")
                        .HasFilter("\"status\" = 'active'");

                    b.ToTable("refresh_sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_sessions_expiration", "\"expires_at\" > \"created_at\"");

                            t.HasCheckConstraint("ck_refresh_sessions_revoked", "(\"status\" = 'revoked' AND \"revoked_at\" IS NOT NULL) OR (\"status\" <> 'revoked' AND \"revoked_at\" IS NULL)");

                            t.HasCheckConstraint("ck_refresh_sessions_rotation", "(\"rotated_at\" IS NULL AND \"replaced_by_session_id\" IS NULL) OR (\"rotated_at\" IS NOT NULL AND \"replaced_by_session_id\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_refresh_sessions_status", "\"status\" IN ('active', 'revoked', 'expired')");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.CareRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<Guid>("ManagerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_profile_id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("relationship_type");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_profile_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_care_relationships");

                    b.HasIndex("CreatedByAccountId")
                        .HasDatabaseName("ix_care_relationships_created_by_account_id");

                    b.HasIndex("RevokedByAccountId")
                        .HasDatabaseName("ix_care_relationships_revoked_by_account_id");

                    b.HasIndex("ManagerProfileId", "Status")
                        .HasDatabaseName("ix_care_relationships_manager_status");

                    b.HasIndex("ManagerProfileId", "SubjectProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_care_relationships_active_manager_subject")
                        .HasFilter("status = 'active'");

                    b.HasIndex("SubjectProfileId", "Status")
                        .HasDatabaseName("ix_care_relationships_subject_status");

                    b.ToTable("care_relationships", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_care_relationships_attestation_timestamp", "attested_at <= created_at");

                            t.HasCheckConstraint("ck_care_relationships_attestation_version", "length(btrim(attestation_version)) > 0");

                            t.HasCheckConstraint("ck_care_relationships_distinct_profiles", "manager_profile_id <> subject_profile_id");

                            t.HasCheckConstraint("ck_care_relationships_revocation", "(status = 'active' AND revoked_at IS NULL AND revoked_by_account_id IS NULL AND updated_at IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL AND revoked_by_account_id IS NOT NULL AND updated_at = revoked_at)");

                            t.HasCheckConstraint("ck_care_relationships_revocation_timestamp", "revoked_at IS NULL OR revoked_at >= created_at");

                            t.HasCheckConstraint("ck_care_relationships_status", "status IN ('active', 'revoked')");

                            t.HasCheckConstraint("ck_care_relationships_type", "relationship_type IN ('parent', 'legal_guardian', 'caregiver', 'spouse', 'child', 'sibling', 'other')");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BeeexyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("beeexy_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("SexAssignedAtBirth")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("sex_assigned_at_birth");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_patient_profiles");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_profiles_account_id");

                    b.HasIndex("BeeexyId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_profiles_beeexy_id");

                    b.ToTable("patient_profiles", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_profiles_first_name", "first_name IS NULL OR length(btrim(first_name)) > 0");

                            t.HasCheckConstraint("ck_patient_profiles_last_name", "last_name IS NULL OR length(btrim(last_name)) > 0");

                            t.HasCheckConstraint("ck_patient_profiles_sex_assigned_at_birth", "sex_assigned_at_birth IS NULL OR sex_assigned_at_birth IN ('male', 'female')");

                            t.HasCheckConstraint("ck_patient_profiles_state", "state IS NULL OR state IN ('AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY')");

                            t.HasCheckConstraint("ck_patient_profiles_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_preferences");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_preferences_account_id");

                    b.ToTable("user_preferences", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_user_preferences_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.ClinicalAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicalRuleSetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinical_rule_set_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("ResultMessageReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("result_message_reference");

                    b.Property<string>("UrgencyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("urgency_code");

                    b.HasKey("Id")
                        .HasName("pk_clinical_assessments");

                    b.HasIndex("ClinicalRuleSetVersionId")
                        .HasDatabaseName("ix_clinical_assessments_clinical_rule_set_version_id");

                    b.HasIndex("EpisodeId")
                        .IsUnique()
                        .HasDatabaseName("ux_clinical_assessments_episode_id");

                    b.HasIndex("EpisodeId", "ClinicalRuleSetVersionId")
                        .HasDatabaseName("ix_clinical_assessments_episode_rule_set_version");

                    b.ToTable("clinical_assessments", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_clinical_assessments_urgency_code", "length(btrim(urgency_code)) > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.ClinicalFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FindingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("finding_code");

                    b.Property<string>("MessageReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_reference");

                    b.Property<string>("SourceRuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_rule_code");

                    b.HasKey("Id")
                        .HasName("pk_clinical_findings");

                    b.HasIndex("AssessmentId", "FindingCode")
                        .IsUnique()
                        .HasDatabaseName("ux_clinical_findings_assessment_finding_code");

                    b.ToTable("clinical_findings", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_clinical_findings_finding_code", "length(btrim(finding_code)) > 0");

                            t.HasCheckConstraint("ck_clinical_findings_source_rule_code", "length(btrim(source_rule_code)) > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.ClinicalRuleSetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("clinical_approval_status");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("clinical_content_source");

                    b.Property<string>("DefinitionMetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_metadata");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Pathway")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pathway_code");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("clinical_review_status");

                    b.Property<string>("RuleSetCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_set_code");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_clinical_rule_set_versions");

                    b.HasIndex("Pathway", "ActivatedAt")
                        .HasDatabaseName("ix_clinical_rule_set_versions_pathway_activation");

                    b.HasIndex("RuleSetCode", "ActivatedAt")
                        .HasDatabaseName("ix_clinical_rule_set_versions_code_activation");

                    b.HasIndex("RuleSetCode", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_clinical_rule_set_versions_code_version");

                    b.ToTable("clinical_rule_set_versions", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_clinical_rule_set_versions_activation", "activated_at IS NULL OR (activated_at >= imported_at AND (approved_at IS NULL OR activated_at >= approved_at))");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_approval", "(clinical_approval_status = 'APPROVED' AND approved_at IS NOT NULL) OR (clinical_approval_status <> 'APPROVED' AND approved_at IS NULL)");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_approval_status", "clinical_approval_status IN ('APPROVED', 'PENDING_FORMAL_REVIEW')");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_code", "length(btrim(rule_set_code)) > 0");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_content_hash", "length(content_hash) >= 32");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_content_source", "clinical_content_source IN ('LEGACY_UNSPECIFIED', 'REFERENCE_PLATFORM_DERIVED')");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_definition_metadata", "jsonb_typeof(definition_metadata) = 'object'");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_pathway", "length(btrim(pathway_code)) > 0");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_review_status", "clinical_review_status IN ('REVIEWED', 'PROVISIONAL')");

                            t.HasCheckConstraint("ck_clinical_rule_set_versions_version", "length(btrim(version)) > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.PreTriageEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymousExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymous_expires_at");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid>("ClinicalRuleSetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinical_rule_set_version_id");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("PatientProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_profile_id");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_version_id");

                    b.Property<Guid>("SourceSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_session_id");

                    b.HasKey("Id")
                        .HasName("pk_pre_triage_episodes");

                    b.HasAlternateKey("Id", "ClinicalRuleSetVersionId")
                        .HasName("ak_pre_triage_episodes_id_clinical_rule_set_version_id");

                    b.HasAlternateKey("Id", "QuestionnaireVersionId")
                        .HasName("ak_pre_triage_episodes_id_questionnaire_version_id");

                    b.HasIndex("AnonymousExpiresAt")
                        .HasDatabaseName("ix_pre_triage_episodes_unclaimed_expiry")
                        .HasFilter("patient_profile_id IS NULL");

                    b.HasIndex("ClinicalRuleSetVersionId")
                        .HasDatabaseName("ix_pre_triage_episodes_clinical_rule_set_version_id");

                    b.HasIndex("QuestionnaireVersionId")
                        .HasDatabaseName("ix_pre_triage_episodes_questionnaire_version_id");

                    b.HasIndex("SourceSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_pre_triage_episodes_source_session_id");

                    b.HasIndex("PatientProfileId", "CompletedAt")
                        .HasDatabaseName("ix_pre_triage_episodes_patient_completed_at");

                    b.HasIndex("SourceSessionId", "QuestionnaireVersionId")
                        .HasDatabaseName("ix_pre_triage_episodes_source_session_version");

                    b.ToTable("pre_triage_episodes", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_pre_triage_episodes_anonymous_claim", "(patient_profile_id IS NULL AND anonymous_expires_at IS NOT NULL AND claimed_at IS NULL) OR (patient_profile_id IS NOT NULL AND ((anonymous_expires_at IS NULL AND claimed_at IS NULL) OR (anonymous_expires_at IS NOT NULL AND claimed_at IS NOT NULL)))");

                            t.HasCheckConstraint("ck_pre_triage_episodes_anonymous_expiration", "anonymous_expires_at IS NULL OR anonymous_expires_at > completed_at");

                            t.HasCheckConstraint("ck_pre_triage_episodes_claim_timestamp", "claimed_at IS NULL OR (claimed_at >= completed_at AND claimed_at < anonymous_expires_at)");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.PreTriageSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousCapabilityHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("anonymous_capability_hash");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("PatientProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_profile_id");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pre_triage_sessions");

                    b.HasAlternateKey("Id", "QuestionnaireVersionId")
                        .HasName("ak_pre_triage_sessions_id_questionnaire_version_id");

                    b.HasIndex("AnonymousCapabilityHash")
                        .IsUnique()
                        .HasDatabaseName("ux_pre_triage_sessions_anonymous_capability_hash")
                        .HasFilter("anonymous_capability_hash IS NOT NULL");

                    b.HasIndex("PatientProfileId")
                        .HasDatabaseName("ix_pre_triage_sessions_patient_profile_id");

                    b.HasIndex("QuestionnaireVersionId")
                        .HasDatabaseName("ix_pre_triage_sessions_questionnaire_version_id");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_pre_triage_sessions_status_expiry");

                    b.ToTable("pre_triage_sessions", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_pre_triage_sessions_completion", "(status = 'active' AND completed_at IS NULL) OR (status = 'completed' AND completed_at IS NOT NULL AND completed_at >= created_at AND completed_at < expires_at)");

                            t.HasCheckConstraint("ck_pre_triage_sessions_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_pre_triage_sessions_ownership", "(patient_profile_id IS NULL AND anonymous_capability_hash IS NOT NULL) OR (patient_profile_id IS NOT NULL AND anonymous_capability_hash IS NULL)");

                            t.HasCheckConstraint("ck_pre_triage_sessions_status", "status IN ('active', 'completed')");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.QuestionnaireDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("clinical_approval_status");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("clinical_content_source");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("Pathway")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pathway_code");

                    b.Property<string>("QuestionnaireCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("questionnaire_code");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("clinical_review_status");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_questionnaire_versions");

                    b.HasIndex("Pathway", "ActivatedAt")
                        .HasDatabaseName("ix_questionnaire_versions_pathway_activation");

                    b.HasIndex("QuestionnaireCode", "ActivatedAt")
                        .HasDatabaseName("ix_questionnaire_versions_code_activation");

                    b.HasIndex("QuestionnaireCode", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_questionnaire_versions_code_version");

                    b.ToTable("questionnaire_versions", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_questionnaire_versions_activation", "activated_at IS NULL OR (activated_at >= imported_at AND (approved_at IS NULL OR activated_at >= approved_at))");

                            t.HasCheckConstraint("ck_questionnaire_versions_approval", "(clinical_approval_status = 'APPROVED' AND approved_at IS NOT NULL) OR (clinical_approval_status <> 'APPROVED' AND approved_at IS NULL)");

                            t.HasCheckConstraint("ck_questionnaire_versions_approval_status", "clinical_approval_status IN ('APPROVED', 'PENDING_FORMAL_REVIEW')");

                            t.HasCheckConstraint("ck_questionnaire_versions_code", "length(btrim(questionnaire_code)) > 0");

                            t.HasCheckConstraint("ck_questionnaire_versions_content_hash", "length(content_hash) >= 32");

                            t.HasCheckConstraint("ck_questionnaire_versions_content_source", "clinical_content_source IN ('LEGACY_UNSPECIFIED', 'REFERENCE_PLATFORM_DERIVED')");

                            t.HasCheckConstraint("ck_questionnaire_versions_pathway", "length(btrim(pathway_code)) > 0");

                            t.HasCheckConstraint("ck_questionnaire_versions_review_status", "clinical_review_status IN ('REVIEWED', 'PROVISIONAL')");

                            t.HasCheckConstraint("ck_questionnaire_versions_version", "length(btrim(version)) > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.ReportedSymptom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("NormalizationSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalization_source");

                    b.Property<DateTimeOffset?>("NormalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("normalized_at");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("original_text");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TerminologyCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("terminology_code");

                    b.Property<string>("TerminologyDisplay")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("terminology_display");

                    b.Property<string>("TerminologySystem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("terminology_system");

                    b.HasKey("Id")
                        .HasName("pk_reported_symptoms");

                    b.HasIndex("EpisodeId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_reported_symptoms_episode_sequence")
                        .HasFilter("episode_id IS NOT NULL");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_reported_symptoms_session_sequence")
                        .HasFilter("session_id IS NOT NULL");

                    b.ToTable("reported_symptoms", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_reported_symptoms_normalization", "(terminology_system IS NULL AND terminology_code IS NULL AND terminology_display IS NULL AND normalization_source IS NULL AND normalized_at IS NULL) OR (terminology_system IS NOT NULL AND terminology_code IS NOT NULL AND normalization_source IS NOT NULL AND normalized_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_reported_symptoms_normalized_at", "normalized_at IS NULL OR normalized_at >= reported_at");

                            t.HasCheckConstraint("ck_reported_symptoms_original_text", "length(btrim(original_text)) > 0");

                            t.HasCheckConstraint("ck_reported_symptoms_owner", "(session_id IS NOT NULL AND episode_id IS NULL) OR (session_id IS NULL AND episode_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_reported_symptoms_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.TriageAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_version_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("EpisodeId", "QuestionnaireVersionId")
                        .HasDatabaseName("ix_answers_episode_questionnaire_version");

                    b.HasIndex("EpisodeId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_answers_episode_sequence")
                        .HasFilter("episode_id IS NOT NULL");

                    b.HasIndex("QuestionId", "QuestionnaireVersionId")
                        .HasDatabaseName("ix_answers_question_questionnaire_version");

                    b.HasIndex("SessionId", "QuestionnaireVersionId")
                        .HasDatabaseName("ix_answers_session_questionnaire_version");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_answers_session_sequence")
                        .HasFilter("session_id IS NOT NULL");

                    b.ToTable("answers", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_answers_owner", "(session_id IS NOT NULL AND episode_id IS NULL) OR (session_id IS NULL AND episode_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_answers_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.TriageQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerSchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_schema");

                    b.Property<string>("BranchingMetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("branching_metadata");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("prompt_text");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("questionnaire_version_id");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasAlternateKey("Id", "QuestionnaireVersionId")
                        .HasName("ak_questions_id_questionnaire_version_id");

                    b.HasIndex("QuestionnaireVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_questions_questionnaire_version_code");

                    b.HasIndex("QuestionnaireVersionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_questions_questionnaire_version_order");

                    b.ToTable("questions", "triage", t =>
                        {
                            t.HasCheckConstraint("ck_questions_code", "length(btrim(code)) > 0");

                            t.HasCheckConstraint("ck_questions_display_order", "display_order > 0");

                            t.HasCheckConstraint("ck_questions_prompt_text", "length(btrim(prompt_text)) > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_accounts_account_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_sessions_accounts_account_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.CareRelationship", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_relationships_accounts_created_by_account_id");

                    b.HasOne("Beeexy.Domain.Patients.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("ManagerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_relationships_patient_profiles_manager_profile_id");

                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("RevokedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_care_relationships_accounts_revoked_by_account_id");

                    b.HasOne("Beeexy.Domain.Patients.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("SubjectProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_relationships_patient_profiles_subject_profile_id");

                    b.OwnsOne("Beeexy.Domain.Patients.AuthorizationAttestation", "Attestation", b1 =>
                        {
                            b1.Property<Guid>("CareRelationshipId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AttestedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("attested_at");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("attestation_version");

                            b1.HasKey("CareRelationshipId");

                            b1.ToTable("care_relationships", "patients");

                            b1.WithOwner()
                                .HasForeignKey("CareRelationshipId");
                        });

                    b.Navigation("Attestation")
                        .IsRequired();
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.PatientProfile", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithOne()
                        .HasForeignKey("Beeexy.Domain.Patients.PatientProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patient_profiles_accounts_account_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.UserPreference", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithOne()
                        .HasForeignKey("Beeexy.Domain.Patients.UserPreference", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_accounts_account_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.ClinicalAssessment", b =>
                {
                    b.HasOne("Beeexy.Domain.Triage.ClinicalRuleSetVersion", null)
                        .WithMany()
                        .HasForeignKey("ClinicalRuleSetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_assessments_rule_set_versions_version_id");

                    b.HasOne("Beeexy.Domain.Triage.PreTriageEpisode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId", "ClinicalRuleSetVersionId")
                        .HasPrincipalKey("Id", "ClinicalRuleSetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_assessments_episodes_episode_rule_set_version");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.ClinicalFinding", b =>
                {
                    b.HasOne("Beeexy.Domain.Triage.ClinicalAssessment", null)
                        .WithMany("Findings")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_findings_clinical_assessments_assessment_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.PreTriageEpisode", b =>
                {
                    b.HasOne("Beeexy.Domain.Triage.ClinicalRuleSetVersion", null)
                        .WithMany()
                        .HasForeignKey("ClinicalRuleSetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pre_triage_episodes_rule_set_versions_version_id");

                    b.HasOne("Beeexy.Domain.Patients.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pre_triage_episodes_patient_profiles_patient_profile_id");

                    b.HasOne("Beeexy.Domain.Triage.QuestionnaireDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pre_triage_episodes_questionnaire_versions_version_id");

                    b.HasOne("Beeexy.Domain.Triage.PreTriageSession", null)
                        .WithMany()
                        .HasForeignKey("SourceSessionId", "QuestionnaireVersionId")
                        .HasPrincipalKey("Id", "QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pre_triage_episodes_sessions_source_session_version");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.PreTriageSession", b =>
                {
                    b.HasOne("Beeexy.Domain.Patients.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pre_triage_sessions_patient_profiles_patient_profile_id");

                    b.HasOne("Beeexy.Domain.Triage.QuestionnaireDefinitionVersion", null)
                        .WithMany()
                        .HasForeignKey("QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pre_triage_sessions_questionnaire_versions_version_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.ReportedSymptom", b =>
                {
                    b.HasOne("Beeexy.Domain.Triage.PreTriageEpisode", null)
                        .WithMany("ReportedSymptoms")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reported_symptoms_pre_triage_episodes_episode_id");

                    b.HasOne("Beeexy.Domain.Triage.PreTriageSession", null)
                        .WithMany("ReportedSymptoms")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_reported_symptoms_pre_triage_sessions_session_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.TriageAnswer", b =>
                {
                    b.HasOne("Beeexy.Domain.Triage.PreTriageEpisode", null)
                        .WithMany("Answers")
                        .HasForeignKey("EpisodeId", "QuestionnaireVersionId")
                        .HasPrincipalKey("Id", "QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_answers_pre_triage_episodes_episode_version");

                    b.HasOne("Beeexy.Domain.Triage.TriageQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId", "QuestionnaireVersionId")
                        .HasPrincipalKey("Id", "QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_version");

                    b.HasOne("Beeexy.Domain.Triage.PreTriageSession", null)
                        .WithMany("Answers")
                        .HasForeignKey("SessionId", "QuestionnaireVersionId")
                        .HasPrincipalKey("Id", "QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_answers_pre_triage_sessions_session_version");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.TriageQuestion", b =>
                {
                    b.HasOne("Beeexy.Domain.Triage.QuestionnaireDefinitionVersion", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_questionnaire_versions_questionnaire_version_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.ClinicalAssessment", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.PreTriageEpisode", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ReportedSymptoms");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.PreTriageSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ReportedSymptoms");
                });

            modelBuilder.Entity("Beeexy.Domain.Triage.QuestionnaireDefinitionVersion", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
