// <auto-generated />
using System;
using Beeexy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beeexy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BeeexyDbContext))]
    [Migration("20260820053544_Phase26ProfileOptimisticConcurrency")]
    partial class Phase26ProfileOptimisticConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beeexy.Domain.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_normalized_email");

                    b.ToTable("accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_accounts_status", "\"status\" IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.EmailAuthenticationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("otp_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_email_authentication_challenges");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_email_authentication_challenges_pending_expiry")
                        .HasFilter("\"status\" = 'pending' AND \"consumed_at\" IS NULL");

                    b.ToTable("email_authentication_challenges", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_email_authentication_challenges_attempt_count", "\"attempt_count\" >= 0");

                            t.HasCheckConstraint("ck_email_authentication_challenges_consumed", "(\"status\" = 'consumed' AND \"consumed_at\" IS NOT NULL) OR (\"status\" <> 'consumed' AND \"consumed_at\" IS NULL)");

                            t.HasCheckConstraint("ck_email_authentication_challenges_expiration", "\"expires_at\" > \"created_at\"");

                            t.HasCheckConstraint("ck_email_authentication_challenges_status", "\"status\" IN ('pending', 'consumed', 'expired')");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_external_identities");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_external_identities_account_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_provider_subject");

                    b.ToTable("external_identities", "identity");
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ParentSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_session_id");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_refresh_sessions");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_sessions_family_id");

                    b.HasIndex("ParentSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_parent_session_id")
                        .HasFilter("\"parent_session_id\" IS NOT NULL");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_refresh_token_hash");

                    b.HasIndex("AccountId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_sessions_active_account_expiry")
                        .HasFilter("\"status\" = 'active'");

                    b.ToTable("refresh_sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_sessions_expiration", "\"expires_at\" > \"created_at\"");

                            t.HasCheckConstraint("ck_refresh_sessions_revoked", "(\"status\" = 'revoked' AND \"revoked_at\" IS NOT NULL) OR (\"status\" <> 'revoked' AND \"revoked_at\" IS NULL)");

                            t.HasCheckConstraint("ck_refresh_sessions_rotation", "(\"rotated_at\" IS NULL AND \"replaced_by_session_id\" IS NULL) OR (\"rotated_at\" IS NOT NULL AND \"replaced_by_session_id\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_refresh_sessions_status", "\"status\" IN ('active', 'revoked', 'expired')");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BeeexyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("beeexy_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_profiles");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_profiles_account_id");

                    b.HasIndex("BeeexyId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_profiles_beeexy_id");

                    b.ToTable("patient_profiles", "patients");
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_preferences");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_preferences_account_id");

                    b.ToTable("user_preferences", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_user_preferences_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_accounts_account_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_sessions_accounts_account_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.PatientProfile", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithOne()
                        .HasForeignKey("Beeexy.Domain.Patients.PatientProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patient_profiles_accounts_account_id");
                });

            modelBuilder.Entity("Beeexy.Domain.Patients.UserPreference", b =>
                {
                    b.HasOne("Beeexy.Domain.Identity.Account", null)
                        .WithOne()
                        .HasForeignKey("Beeexy.Domain.Patients.UserPreference", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_accounts_account_id");
                });
#pragma warning restore 612, 618
        }
    }
}
